version: '3'

services:
    mariadb:
        image: mariadb:10.5
        ports:
          - '3306:3306'
        volumes:
          - db-volume:/var/lib/mysql
        #environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
        #  - ALLOW_EMPTY_PASSWORD=yes
        env_file:
            - moodle_variables.env
        healthcheck:
          test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
          interval: 15s
          timeout: 5s
          retries: 6
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    #dbapp:
    #    image: mysql:5
    #    restart: always
    #    volumes:
    #        - db-volume:/var/lib/mysql
    #    env_file:
    #        - moodle_variables.env
    #    networks:
    #        - backendDB
    #    deploy:
    #        replicas: 1
    #        restart_policy:
    #            condition: any
    moodleapp:
        build: .
        links:
            - mariadb:DB
        depends_on: 
            - mariadb
        restart: always
        volumes:
            - moodleapp-data:/var/moodledata
        ports:
            - 80:80
            - 443:443
        env_file:
            - moodle_variables.env
        #networks:
        #    - backendDB
        #    - frontendWEB
        deploy:
            replicas: 1
            restart_policy:
                condition: any            

volumes: 
    db-volume:
    moodleapp-data:
    mariadb_data:
        driver: local

networks:
    backendDB:
    frontendWEB: